# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '10c849f6-3513-4389-b6de-d4232eed0a54'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    overrideParameters: '-projectName ARM-01 -linkedTemplateUri https://raw.githubusercontent.com/KetanPatel83/IAC-AzureRmPipeline-repo/master/azuredeploy.json?token=AN5AZOUXDCY6IUBTBMMLZ7K7LCEDM'
    deploymentMode: 'Incremental'

